apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiosk-admin
  namespace: production
  labels:
    app: kiosk-admin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: kiosk-admin
  template:
    metadata:
      namespace: production
      labels:
        app: kiosk-admin
    spec:
      containers:
      - name: kiosk-admin
        image: cr.yandex/crpbchff05ai3nceeln1/kiosk-admin:1.0.15
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      imagePullSecrets:
      - name: gitlabregistrycred
